name: Deploy preview to GitHub Pages

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: extract_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi

      - name: Remove workflow artifacts from output
        run: rm -rf .git .github

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: preview/${{ steps.extract_branch.outputs.branch_name }}

      - name: Show preview URL
        run: echo "Preview: https://shek-hrd.github.io/chatter/preview/${{ steps.extract_branch.outputs.branch_name }}/"